#!/usr/bin/env bash
# Does the following:
#   Create a file /var/run/myscript.pid containing the script PID.
#   Displays "To infinity and beyond" indefinitely
#   Displays "I hate the kill command" upon receiving a SIGTERM
#   Displays "Y U no love me?!" upon receiving a SIGINT
#   Deletes the file /var/run/myscript.pid and terminates upon
#+  receiving a SIGQUIT or SIGTERM.


terminate_handler() {
    echo "I hate the kill command"
    rm -f /var/run/myscript.pid
    exit 0
}

interrupt_handler() {
    echo "Y U no love me?!"
}

trap 'terminate_handler' SIGTERM SIGQUIT
trap 'interrupt_handler' SIGINT

echo "$$" > /var/run/myscript.pid

while true
do
    echo "To infinity and beyond"
    sleep 1
done