#!/usr/bin/env bash
# This script displays specific fields from the /etc/passwd file

while IFS=: read -r username password uid gid gecos home shell; do
    echo "$username:$uid:$home"
done < /etc/passwd