#!/usr/bin/env bash
# Set IFS to ':' to parse /etc/passwd fields

IFS=':'
while read -r username password uid gid info homedir shell; do
    # Print the formatted user information
    echo "The user $username is part of the $gid gang, lives in $homedir, and rides $shell."
    echo "User ID's place is protected by the passcode $password."
    echo "More info about the user here: $info"
    echo ""
done < /etc/passwd
