#!/usr/bin/env bash
# This script parses Apache log files in list format.
# It groups visitors by IP and HTTP status code.
# It also displays the number of occurrences, IP, and HTTP status
#+  code of each log, in sorted order.

awk '{ print $1 " " $9}' apache-access.log | sort | uniq -c | sort -rn
