#!/usr/bin/env bash
# This script displays numbers from 1 to 20 and displays specific messages for certain loop iterations

counter=1

while (( counter <= 20 )); do
    echo $counter
    
    case $counter in
        4)
            echo "bad luck from China"
            ;;
        9)
            echo "bad luck from Japan"
            ;;
        17)
            echo "bad luck from Italy"
            ;;
        *)
            ;;
    esac
    
    ((counter++))
done
