#!/usr/bin/env bash
# This script displays numbers from 1 to 20 and displays specific messages for certain loop iterations

counter=0

while (( counter < 20 )); do
    echo $counter
    
    case $counter in
        3)
            echo "bad luck from China"
            ;;
        8)
            echo "bad luck from Japan"
            ;;
        16)
            echo "bad luck from Italy"
            ;;
        *)
            ;;
    esac
    
    ((counter++))
done