#!/usr/bin/env bash
# This script displays the time for 12 hours and 59 minutes

hour=0
minute=1

while (( hour <= 12 )); do

    printf "%02d:%02d\n" $hour $minute
    
    ((minute++))
    if (( minute == 60 )); then
        minute=0
        ((hour++))
    fi
done